version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    environment:
      NODE_ENV: production
      PROD_DB_URL: postgres://postgres:postgres@db:5432/postgres
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  db_data:
